const map = {
    jermaMoon: "<img alt='jermaMoon' title='jermaMoon' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/79428/1.0'>", 
    jermaSun: "<img alt='jermaSun' title='jermaSun' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/87845/1.0'>", 
    jermaGlue: "<img alt='jermaGlue' title='jermaGlue' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/91793/1.0'>", 
    jermaEgg: "<img alt='jermaEgg' title='jermaEgg' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/91801/1.0'>", 
    jermaJup1: "<img alt='jermaJup1' title='jermaJup1' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/91806/1.0'>", 
    jermaJup2: "<img alt='jermaJup2' title='jermaJup2' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/91807/1.0'>", 
    jermaJup3: "<img alt='jermaJup3' title='jermaJup3' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/91808/1.0'>", 
    jermaJup4: "<img alt='jermaJup4' title='jermaJup4' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/91809/1.0'>", 
    jermaSlug: "<img alt='jermaSlug' title='jermaSlug' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/156949/1.0'>", 
    jermaComet: "<img alt='jermaComet' title='jermaComet' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/156950/1.0'>", 
    jermaSaturn: "<img alt='jermaSaturn' title='jermaSaturn' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/156951/1.0'>", 
    jermaRat: "<img alt='jermaRat' title='jermaRat' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/156952/1.0'>", 
    jermaFear: "<img alt='jermaFear' title='jermaFear' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/157199/1.0'>", 
    jermaMars: "<img alt='jermaMars' title='jermaMars' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/160423/1.0'>", 
    jermaPluto: "<img alt='jermaPluto' title='jermaPluto' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/945503/1.0'>", 
    jermaEarth: "<img alt='jermaEarth' title='jermaEarth' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/945557/1.0'>", 
    jermaBld: "<img alt='jermaBld' title='jermaBld' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/945731/1.0'>", 
    jermaMustard: "<img alt='jermaMustard' title='jermaMustard' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/948665/1.0'>", 
    jermaSnort: "<img alt='jermaSnort' title='jermaSnort' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/972178/1.0'>", 
    jermaMerc: "<img alt='jermaMerc' title='jermaMerc' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1096262/1.0'>", 
    jermaJex2: "<img alt='jermaJex2' title='jermaJex2' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1096265/1.0'>", 
    jermaJex: "<img alt='jermaJex' title='jermaJex' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1096266/1.0'>", 
    jermaNosewipe: "<img alt='jermaNosewipe' title='jermaNosewipe' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1279921/1.0'>", 
    jermaDafoe: "<img alt='jermaDafoe' title='jermaDafoe' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1279939/1.0'>", 
    jermaIQ: "<img alt='jermaIQ' title='jermaIQ' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1279941/1.0'>", 
    jermaDisgust: "<img alt='jermaDisgust' title='jermaDisgust' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1279953/1.0'>", 
    jermaPain: "<img alt='jermaPain' title='jermaPain' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1279963/1.0'>", 
    jermaFireman: "<img alt='jermaFireman' title='jermaFireman' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1279967/1.0'>", 
    jermaHeart: "<img alt='jermaHeart' title='jermaHeart' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1279975/1.0'>", 
    jermaTV: "<img alt='jermaTV' title='jermaTV' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1279984/1.0'>", 
    jermaVenus: "<img alt='jermaVenus' title='jermaVenus' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1279994/1.0'>", 
    jermaChomp: "<img alt='jermaChomp' title='jermaChomp' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1279998/1.0'>", 
    jermaOneguy: "<img alt='jermaOneguy' title='jermaOneguy' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1803546/1.0'>", 
    jermaOld: "<img alt='jermaOld' title='jermaOld' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1803693/1.0'>", 
    jermaPop: "<img alt='jermaPop' title='jermaPop' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/300258117/1.0'>", 
    jermaSour: "<img alt='jermaSour' title='jermaSour' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/300921190/1.0'>", 
    jermaThing: "<img alt='jermaThing' title='jermaThing' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/303166318/1.0'>", 
    jermaGrin: "<img alt='jermaGrin' title='jermaGrin' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/303166400/1.0'>", 
    jermaRatS: "<img alt='jermaRatS' title='jermaRatS' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/303166517/1.0'>", 
    jermaGB: "<img alt='jermaGB' title='jermaGB' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1096260/1.0'>", 
    JKanStyle: "<img alt='JKanStyle' title='JKanStyle' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/15/1.0'>", 
    OptimizePrime: "<img alt='OptimizePrime' title='OptimizePrime' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/16/1.0'>", 
    StoneLightning: "<img alt='StoneLightning' title='StoneLightning' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/17/1.0'>", 
    TheRinger: "<img alt='TheRinger' title='TheRinger' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/18/1.0'>", 
    RedCoat: "<img alt='RedCoat' title='RedCoat' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/22/1.0'>", 
    Kappa: "<img alt='Kappa' title='Kappa' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/25/1.0'>", 
    JonCarnage: "<img alt='JonCarnage' title='JonCarnage' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/26/1.0'>", 
    MrDestructoid: "<img alt='MrDestructoid' title='MrDestructoid' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/28/1.0'>", 
    BCWarrior: "<img alt='BCWarrior' title='BCWarrior' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/30/1.0'>", 
    GingerPower: "<img alt='GingerPower' title='GingerPower' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/32/1.0'>", 
    DansGame: "<img alt='DansGame' title='DansGame' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/33/1.0'>", 
    SwiftRage: "<img alt='SwiftRage' title='SwiftRage' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/34/1.0'>", 
    PJSalt: "<img alt='PJSalt' title='PJSalt' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/36/1.0'>", 
    KevinTurtle: "<img alt='KevinTurtle' title='KevinTurtle' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/40/1.0'>", 
    Kreygasm: "<img alt='Kreygasm' title='Kreygasm' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/41/1.0'>", 
    SSSsss: "<img alt='SSSsss' title='SSSsss' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/46/1.0'>", 
    PunchTrees: "<img alt='PunchTrees' title='PunchTrees' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/47/1.0'>", 
    ArsonNoSexy: "<img alt='ArsonNoSexy' title='ArsonNoSexy' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/50/1.0'>", 
    SMOrc: "<img alt='SMOrc' title='SMOrc' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/52/1.0'>", 
    FrankerZ: "<img alt='FrankerZ' title='FrankerZ' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/65/1.0'>", 
    OneHand: "<img alt='OneHand' title='OneHand' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/66/1.0'>", 
    BloodTrail: "<img alt='BloodTrail' title='BloodTrail' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/69/1.0'>", 
    DBstyle: "<img alt='DBstyle' title='DBstyle' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/73/1.0'>", 
    AsianGlow: "<img alt='AsianGlow' title='AsianGlow' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/74/1.0'>", 
    BibleThump: "<img alt='BibleThump' title='BibleThump' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/86/1.0'>", 
    ShazBotstix: "<img alt='ShazBotstix' title='ShazBotstix' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/87/1.0'>", 
    PMSTwin: "<img alt='PMSTwin' title='PMSTwin' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/92/1.0'>", 
    FUNgineer: "<img alt='FUNgineer' title='FUNgineer' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/244/1.0'>", 
    ResidentSleeper: "<img alt='ResidentSleeper' title='ResidentSleeper' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/245/1.0'>", 
    HotPokket: "<img alt='HotPokket' title='HotPokket' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/357/1.0'>", 
    FailFish: "<img alt='FailFish' title='FailFish' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/360/1.0'>", 
    DAESuppy: "<img alt='DAESuppy' title='DAESuppy' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/973/1.0'>", 
    WholeWheat: "<img alt='WholeWheat' title='WholeWheat' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1896/1.0'>", 
    ThunBeast: "<img alt='ThunBeast' title='ThunBeast' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1898/1.0'>", 
    TF2John: "<img alt='TF2John' title='TF2John' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1899/1.0'>", 
    RalpherZ: "<img alt='RalpherZ' title='RalpherZ' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1900/1.0'>", 
    Kippa: "<img alt='Kippa' title='Kippa' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1901/1.0'>", 
    Keepo: "<img alt='Keepo' title='Keepo' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1902/1.0'>", 
    BigBrother: "<img alt='BigBrother' title='BigBrother' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1904/1.0'>", 
    SoBayed: "<img alt='SoBayed' title='SoBayed' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1906/1.0'>", 
    PeoplesChamp: "<img alt='PeoplesChamp' title='PeoplesChamp' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/3412/1.0'>", 
    GrammarKing: "<img alt='GrammarKing' title='GrammarKing' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/3632/1.0'>", 
    PanicVis: "<img alt='PanicVis' title='PanicVis' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/3668/1.0'>", 
    ANELE: "<img alt='ANELE' title='ANELE' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/3792/1.0'>", 
    BrokeBack: "<img alt='BrokeBack' title='BrokeBack' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/4057/1.0'>", 
    PipeHype: "<img alt='PipeHype' title='PipeHype' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/4240/1.0'>", 
    YouWHY: "<img alt='YouWHY' title='YouWHY' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/4337/1.0'>", 
    RitzMitz: "<img alt='RitzMitz' title='RitzMitz' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/4338/1.0'>", 
    EleGiggle: "<img alt='EleGiggle' title='EleGiggle' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/4339/1.0'>", 
    TheThing: "<img alt='TheThing' title='TheThing' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/7427/1.0'>", 
    HassaanChop: "<img alt='HassaanChop' title='HassaanChop' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/20225/1.0'>", 
    BabyRage: "<img alt='BabyRage' title='BabyRage' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/22639/1.0'>", 
    panicBasket: "<img alt='panicBasket' title='panicBasket' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/22998/1.0'>", 
    PermaSmug: "<img alt='PermaSmug' title='PermaSmug' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/27509/1.0'>", 
    BuddhaBar: "<img alt='BuddhaBar' title='BuddhaBar' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/27602/1.0'>", 
    WutFace: "<img alt='WutFace' title='WutFace' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/28087/1.0'>", 
    PRChase: "<img alt='PRChase' title='PRChase' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/28328/1.0'>", 
    Mau5: "<img alt='Mau5' title='Mau5' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/30134/1.0'>", 
    HeyGuys: "<img alt='HeyGuys' title='HeyGuys' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/30259/1.0'>", 
    NotATK: "<img alt='NotATK' title='NotATK' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/34875/1.0'>", 
    mcaT: "<img alt='mcaT' title='mcaT' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/35063/1.0'>", 
    TTours: "<img alt='TTours' title='TTours' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/38436/1.0'>", 
    PraiseIt: "<img alt='PraiseIt' title='PraiseIt' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/38586/1.0'>", 
    CorgiDerp: "<img alt='CorgiDerp' title='CorgiDerp' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/49106/1.0'>", 
    ArgieB8: "<img alt='ArgieB8' title='ArgieB8' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/51838/1.0'>", 
    ShadyLulu: "<img alt='ShadyLulu' title='ShadyLulu' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/52492/1.0'>", 
    KappaPride: "<img alt='KappaPride' title='KappaPride' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/55338/1.0'>", 
    CoolCat: "<img alt='CoolCat' title='CoolCat' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/58127/1.0'>", 
    DendiFace: "<img alt='DendiFace' title='DendiFace' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/58135/1.0'>", 
    NotLikeThis: "<img alt='NotLikeThis' title='NotLikeThis' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/58765/1.0'>", 
    riPepperonis: "<img alt='riPepperonis' title='riPepperonis' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/62833/1.0'>", 
    duDudu: "<img alt='duDudu' title='duDudu' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/62834/1.0'>", 
    bleedPurple: "<img alt='bleedPurple' title='bleedPurple' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/62835/1.0'>", 
    twitchRaid: "<img alt='twitchRaid' title='twitchRaid' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/62836/1.0'>", 
    SeemsGood: "<img alt='SeemsGood' title='SeemsGood' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/64138/1.0'>", 
    MingLee: "<img alt='MingLee' title='MingLee' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/68856/1.0'>", 
    KappaRoss: "<img alt='KappaRoss' title='KappaRoss' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/70433/1.0'>", 
    KappaClaus: "<img alt='KappaClaus' title='KappaClaus' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/74510/1.0'>", 
    OhMyDog: "<img alt='OhMyDog' title='OhMyDog' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/81103/1.0'>", 
    OSFrog: "<img alt='OSFrog' title='OSFrog' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/81248/1.0'>", 
    SeriousSloth: "<img alt='SeriousSloth' title='SeriousSloth' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/81249/1.0'>", 
    KomodoHype: "<img alt='KomodoHype' title='KomodoHype' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/81273/1.0'>", 
    VoHiYo: "<img alt='VoHiYo' title='VoHiYo' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/81274/1.0'>", 
    MikeHogu: "<img alt='MikeHogu' title='MikeHogu' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/81636/1.0'>", 
    KappaWealth: "<img alt='KappaWealth' title='KappaWealth' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/81997/1.0'>", 
    cmonBruh: "<img alt='cmonBruh' title='cmonBruh' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/84608/1.0'>", 
    SmoocherZ: "<img alt='SmoocherZ' title='SmoocherZ' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/89945/1.0'>", 
    NomNom: "<img alt='NomNom' title='NomNom' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/90075/1.0'>", 
    StinkyCheese: "<img alt='StinkyCheese' title='StinkyCheese' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/90076/1.0'>", 
    ChefFrank: "<img alt='ChefFrank' title='ChefFrank' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/90129/1.0'>", 
    FutureMan: "<img alt='FutureMan' title='FutureMan' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/98562/1.0'>", 
    OpieOP: "<img alt='OpieOP' title='OpieOP' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/100590/1.0'>", 
    DoritosChip: "<img alt='DoritosChip' title='DoritosChip' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/102242/1.0'>", 
    PJSugar: "<img alt='PJSugar' title='PJSugar' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/102556/1.0'>", 
    VoteYea: "<img alt='VoteYea' title='VoteYea' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/106293/1.0'>", 
    VoteNay: "<img alt='VoteNay' title='VoteNay' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/106294/1.0'>", 
    RuleFive: "<img alt='RuleFive' title='RuleFive' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/107030/1.0'>", 
    DxCat: "<img alt='DxCat' title='DxCat' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/110734/1.0'>", 
    DrinkPurple: "<img alt='DrinkPurple' title='DrinkPurple' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/110785/1.0'>", 
    TinyFace: "<img alt='TinyFace' title='TinyFace' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/111119/1.0'>", 
    PicoMause: "<img alt='PicoMause' title='PicoMause' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/111300/1.0'>", 
    TheTarFu: "<img alt='TheTarFu' title='TheTarFu' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/111351/1.0'>", 
    DatSheffy: "<img alt='DatSheffy' title='DatSheffy' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/111700/1.0'>", 
    UnSane: "<img alt='UnSane' title='UnSane' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/111792/1.0'>", 
    copyThis: "<img alt='copyThis' title='copyThis' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/112288/1.0'>", 
    pastaThat: "<img alt='pastaThat' title='pastaThat' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/112289/1.0'>", 
    imGlitch: "<img alt='imGlitch' title='imGlitch' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/112290/1.0'>", 
    GivePLZ: "<img alt='GivePLZ' title='GivePLZ' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/112291/1.0'>", 
    TakeNRG: "<img alt='TakeNRG' title='TakeNRG' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/112292/1.0'>", 
    BlargNaut: "<img alt='BlargNaut' title='BlargNaut' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/114738/1.0'>", 
    DogFace: "<img alt='DogFace' title='DogFace' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/114835/1.0'>", 
    Jebaited: "<img alt='Jebaited' title='Jebaited' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/114836/1.0'>", 
    TooSpicy: "<img alt='TooSpicy' title='TooSpicy' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/114846/1.0'>", 
    WTRuck: "<img alt='WTRuck' title='WTRuck' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/114847/1.0'>", 
    UncleNox: "<img alt='UncleNox' title='UncleNox' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/114856/1.0'>", 
    RaccAttack: "<img alt='RaccAttack' title='RaccAttack' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/114870/1.0'>", 
    StrawBeary: "<img alt='StrawBeary' title='StrawBeary' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/114876/1.0'>", 
    PrimeMe: "<img alt='PrimeMe' title='PrimeMe' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/115075/1.0'>", 
    BrainSlug: "<img alt='BrainSlug' title='BrainSlug' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/115233/1.0'>", 
    BatChest: "<img alt='BatChest' title='BatChest' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/115234/1.0'>", 
    CurseLit: "<img alt='CurseLit' title='CurseLit' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/116625/1.0'>", 
    Poooound: "<img alt='Poooound' title='Poooound' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/117484/1.0'>", 
    FreakinStinkin: "<img alt='FreakinStinkin' title='FreakinStinkin' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/117701/1.0'>", 
    SuperVinlin: "<img alt='SuperVinlin' title='SuperVinlin' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/118772/1.0'>", 
    TriHard: "<img alt='TriHard' title='TriHard' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/120232/1.0'>", 
    CoolStoryBob: "<img alt='CoolStoryBob' title='CoolStoryBob' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/123171/1.0'>", 
    ItsBoshyTime: "<img alt='ItsBoshyTime' title='ItsBoshyTime' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/133468/1.0'>", 
    KAPOW: "<img alt='KAPOW' title='KAPOW' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/133537/1.0'>", 
    YouDontSay: "<img alt='YouDontSay' title='YouDontSay' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/134254/1.0'>", 
    UWot: "<img alt='UWot' title='UWot' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/134255/1.0'>", 
    RlyTho: "<img alt='RlyTho' title='RlyTho' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/134256/1.0'>", 
    PartyTime: "<img alt='PartyTime' title='PartyTime' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/135393/1.0'>", 
    NinjaGrumpy: "<img alt='NinjaGrumpy' title='NinjaGrumpy' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/138325/1.0'>", 
    MVGame: "<img alt='MVGame' title='MVGame' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/142140/1.0'>", 
    TBAngel: "<img alt='TBAngel' title='TBAngel' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/143490/1.0'>", 
    TheIlluminati: "<img alt='TheIlluminati' title='TheIlluminati' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/145315/1.0'>", 
    MorphinTime: "<img alt='MorphinTime' title='MorphinTime' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/156787/1.0'>", 
    ThankEgg: "<img alt='ThankEgg' title='ThankEgg' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/160392/1.0'>", 
    BegWan: "<img alt='BegWan' title='BegWan' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/160394/1.0'>", 
    BigPhish: "<img alt='BigPhish' title='BigPhish' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/160395/1.0'>", 
    InuyoFace: "<img alt='InuyoFace' title='InuyoFace' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/160396/1.0'>", 
    Kappu: "<img alt='Kappu' title='Kappu' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/160397/1.0'>", 
    KonCha: "<img alt='KonCha' title='KonCha' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/160400/1.0'>", 
    PunOko: "<img alt='PunOko' title='PunOko' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/160401/1.0'>", 
    SabaPing: "<img alt='SabaPing' title='SabaPing' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/160402/1.0'>", 
    TearGlove: "<img alt='TearGlove' title='TearGlove' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/160403/1.0'>", 
    TehePelo: "<img alt='TehePelo' title='TehePelo' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/160404/1.0'>", 
    TwitchLit: "<img alt='TwitchLit' title='TwitchLit' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/166263/1.0'>", 
    CarlSmile: "<img alt='CarlSmile' title='CarlSmile' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/166266/1.0'>", 
    CrreamAwk: "<img alt='CrreamAwk' title='CrreamAwk' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/191313/1.0'>", 
    Squid1: "<img alt='Squid1' title='Squid1' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/191762/1.0'>", 
    Squid2: "<img alt='Squid2' title='Squid2' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/191763/1.0'>", 
    Squid3: "<img alt='Squid3' title='Squid3' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/191764/1.0'>", 
    Squid4: "<img alt='Squid4' title='Squid4' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/191767/1.0'>", 
    TwitchUnity: "<img alt='TwitchUnity' title='TwitchUnity' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/196892/1.0'>", 
    TPcrunchyroll: "<img alt='TPcrunchyroll' title='TPcrunchyroll' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/323914/1.0'>", 
    EntropyWins: "<img alt='EntropyWins' title='EntropyWins' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/376765/1.0'>", 
    LUL: "<img alt='LUL' title='LUL' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/425618/1.0'>", 
    PowerUpR: "<img alt='PowerUpR' title='PowerUpR' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/425671/1.0'>", 
    PowerUpL: "<img alt='PowerUpL' title='PowerUpL' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/425688/1.0'>", 
    HSCheers: "<img alt='HSCheers' title='HSCheers' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/444572/1.0'>", 
    HSWP: "<img alt='HSWP' title='HSWP' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/446979/1.0'>", 
    DarkMode: "<img alt='DarkMode' title='DarkMode' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/461298/1.0'>", 
    TwitchVotes: "<img alt='TwitchVotes' title='TwitchVotes' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/479745/1.0'>", 
    TPFufun: "<img alt='TPFufun' title='TPFufun' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/508650/1.0'>", 
    RedTeam: "<img alt='RedTeam' title='RedTeam' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/530888/1.0'>", 
    GreenTeam: "<img alt='GreenTeam' title='GreenTeam' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/530890/1.0'>", 
    PurpleStar: "<img alt='PurpleStar' title='PurpleStar' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/624501/1.0'>", 
    FBtouchdown: "<img alt='FBtouchdown' title='FBtouchdown' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/626795/1.0'>", 
    PopCorn: "<img alt='PopCorn' title='PopCorn' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/724216/1.0'>", 
    TombRaid: "<img alt='TombRaid' title='TombRaid' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/864205/1.0'>", 
    EarthDay: "<img alt='EarthDay' title='EarthDay' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/959018/1.0'>", 
    PartyHat: "<img alt='PartyHat' title='PartyHat' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/965738/1.0'>", 
    MercyWing1: "<img alt='MercyWing1' title='MercyWing1' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1003187/1.0'>", 
    MercyWing2: "<img alt='MercyWing2' title='MercyWing2' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1003189/1.0'>", 
    PinkMercy: "<img alt='PinkMercy' title='PinkMercy' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1003190/1.0'>", 
    BisexualPride: "<img alt='BisexualPride' title='BisexualPride' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1064987/1.0'>", 
    LesbianPride: "<img alt='LesbianPride' title='LesbianPride' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1064988/1.0'>", 
    GayPride: "<img alt='GayPride' title='GayPride' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1064991/1.0'>", 
    TransgenderPride: "<img alt='TransgenderPride' title='TransgenderPride' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1064995/1.0'>", 
    AsexualPride: "<img alt='AsexualPride' title='AsexualPride' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1130348/1.0'>", 
    PansexualPride: "<img alt='PansexualPride' title='PansexualPride' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1130349/1.0'>", 
    TwitchRPG: "<img alt='TwitchRPG' title='TwitchRPG' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1220086/1.0'>", 
    IntersexPride: "<img alt='IntersexPride' title='IntersexPride' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1221184/1.0'>", 
    MaxLOL: "<img alt='MaxLOL' title='MaxLOL' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1290325/1.0'>", 
    NonBinaryPride: "<img alt='NonBinaryPride' title='NonBinaryPride' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1297279/1.0'>", 
    GenderFluidPride: "<img alt='GenderFluidPride' title='GenderFluidPride' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1297281/1.0'>", 
    FBRun: "<img alt='FBRun' title='FBRun' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1441261/1.0'>", 
    FBPass: "<img alt='FBPass' title='FBPass' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1441271/1.0'>", 
    FBSpiral: "<img alt='FBSpiral' title='FBSpiral' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1441273/1.0'>", 
    FBBlock: "<img alt='FBBlock' title='FBBlock' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1441276/1.0'>", 
    FBCatch: "<img alt='FBCatch' title='FBCatch' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1441281/1.0'>", 
    FBChallenge: "<img alt='FBChallenge' title='FBChallenge' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1441285/1.0'>", 
    FBPenalty: "<img alt='FBPenalty' title='FBPenalty' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1441289/1.0'>", 
    PixelBob: "<img alt='PixelBob' title='PixelBob' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1547903/1.0'>", 
    GunRun: "<img alt='GunRun' title='GunRun' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1584743/1.0'>", 
    HolidayCookie: "<img alt='HolidayCookie' title='HolidayCookie' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1713813/1.0'>", 
    HolidayLog: "<img alt='HolidayLog' title='HolidayLog' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1713816/1.0'>", 
    HolidayOrnament: "<img alt='HolidayOrnament' title='HolidayOrnament' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1713818/1.0'>", 
    HolidayPresent: "<img alt='HolidayPresent' title='HolidayPresent' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1713819/1.0'>", 
    HolidaySanta: "<img alt='HolidaySanta' title='HolidaySanta' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1713822/1.0'>", 
    HolidayTree: "<img alt='HolidayTree' title='HolidayTree' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1713825/1.0'>", 
    SoonerLater: "<img alt='SoonerLater' title='SoonerLater' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/2113050/1.0'>", 
    TwitchSings: "<img alt='TwitchSings' title='TwitchSings' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/300116344/1.0'>", 
    SingsMic: "<img alt='SingsMic' title='SingsMic' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/300116349/1.0'>", 
    SingsNote: "<img alt='SingsNote' title='SingsNote' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/300116350/1.0'>", 
    PorscheWIN: "<img alt='PorscheWIN' title='PorscheWIN' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/300745158/1.0'>", 
    BOP: "<img alt='BOP' title='BOP' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/301428702/1.0'>", 
    VirtualHug: "<img alt='VirtualHug' title='VirtualHug' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/301696583/1.0'>", 
    ExtraLife: "<img alt='ExtraLife' title='ExtraLife' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/302426269/1.0'>", 
    BlackLivesMatter: "<img alt='BlackLivesMatter' title='BlackLivesMatter' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/302537250/1.0'>", 
    FootBall: "<img alt='FootBall' title='FootBall' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/302628600/1.0'>", 
    FootYellow: "<img alt='FootYellow' title='FootYellow' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/302628613/1.0'>", 
    FootGoal: "<img alt='FootGoal' title='FootGoal' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/302628617/1.0'>", 
    ShowOfHands: "<img alt='ShowOfHands' title='ShowOfHands' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/303564554/1.0'>", 
    GlitchCat: "<img alt='GlitchCat' title='GlitchCat' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/304486301/1.0'>", 
    StinkyGlitch: "<img alt='StinkyGlitch' title='StinkyGlitch' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/304486324/1.0'>", 
    GlitchLit: "<img alt='GlitchLit' title='GlitchLit' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/304489128/1.0'>", 
    GlitchNRG: "<img alt='GlitchNRG' title='GlitchNRG' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/304489309/1.0'>", 
    Awwdible: "<img alt='Awwdible' title='Awwdible' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/304845766/1.0'>", 
    PogChamp: "<img alt='PogChamp' title='PogChamp' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/305748917/1.0'>", 
    CiGrip: "<img alt='CiGrip' title='CiGrip' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/54fa8fce01e468494b85b53c/1x'>", 
    DatSauce: "<img alt='DatSauce' title='DatSauce' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/54fa903b01e468494b85b53f/1x'>", 
    ForeverAlone: "<img alt='ForeverAlone' title='ForeverAlone' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/54fa909b01e468494b85b542/1x'>", 
    GabeN: "<img alt='GabeN' title='GabeN' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/54fa90ba01e468494b85b543/1x'>", 
    HailHelix: "<img alt='HailHelix' title='HailHelix' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/54fa90f201e468494b85b545/1x'>", 
    ShoopDaWhoop: "<img alt='ShoopDaWhoop' title='ShoopDaWhoop' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/54fa932201e468494b85b555/1x'>", 
    bttvNice: "<img alt='bttvNice' title='bttvNice' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/54fab7d2633595ca4c713abf/1x'>", 
    TwaT: "<img alt='TwaT' title='TwaT' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/54fa935601e468494b85b557/1x'>", 
    WatChuSay: "<img alt='WatChuSay' title='WatChuSay' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/54fa99b601e468494b85b55d/1x'>", 
    tehPoleCat: "<img alt='tehPoleCat' title='tehPoleCat' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/566ca11a65dbbdab32ec0558/1x'>", 
    AngelThump: "<img alt='AngelThump' title='AngelThump' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/566ca1a365dbbdab32ec055b/1x'>", 
    TaxiBro: "<img alt='TaxiBro' title='TaxiBro' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/54fbefeb01abde735115de5b/1x'>", 
    BroBalt: "<img alt='BroBalt' title='BroBalt' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/54fbf00a01abde735115de5c/1x'>", 
    CandianRage: "<img alt='CandianRage' title='CandianRage' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/54fbf09c01abde735115de61/1x'>", 
    VisLaud: "<img alt='VisLaud' title='VisLaud' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/550352766f86a5b26c281ba2/1x'>", 
    KaRappa: "<img alt='KaRappa' title='KaRappa' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/550b344bff8ecee922d2a3c1/1x'>", 
    FishMoley: "<img alt='FishMoley' title='FishMoley' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/566ca00f65dbbdab32ec0544/1x'>", 
    Hhhehehe: "<img alt='Hhhehehe' title='Hhhehehe' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/566ca02865dbbdab32ec0547/1x'>", 
    KKona: "<img alt='KKona' title='KKona' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/566ca04265dbbdab32ec054a/1x'>", 
    PoleDoge: "<img alt='PoleDoge' title='PoleDoge' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/566ca09365dbbdab32ec0555/1x'>", 
    sosGame: "<img alt='sosGame' title='sosGame' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/553b48a21f145f087fc15ca6/1x'>", 
    CruW: "<img alt='CruW' title='CruW' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/55471c2789d53f2d12781713/1x'>", 
    RarePepe: "<img alt='RarePepe' title='RarePepe' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/555015b77676617e17dd2e8e/1x'>", 
    haHAA: "<img alt='haHAA' title='haHAA' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/555981336ba1901877765555/1x'>", 
    FeelsBirthdayMan: "<img alt='FeelsBirthdayMan' title='FeelsBirthdayMan' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/55b6524154eefd53777b2580/1x'>", 
    RonSmug: "<img alt='RonSmug' title='RonSmug' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/55f324c47f08be9f0a63cce0/1x'>", 
    KappaCool: "<img alt='KappaCool' title='KappaCool' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/560577560874de34757d2dc0/1x'>", 
    FeelsBadMan: "<img alt='FeelsBadMan' title='FeelsBadMan' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/566c9fc265dbbdab32ec053b/1x'>", 
    bUrself: "<img alt='bUrself' title='bUrself' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/566c9f3b65dbbdab32ec052e/1x'>", 
    ConcernDoge: "<img alt='ConcernDoge' title='ConcernDoge' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/566c9f6365dbbdab32ec0532/1x'>", 
    FeelsGoodMan: "<img alt='FeelsGoodMan' title='FeelsGoodMan' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/566c9fde65dbbdab32ec053e/1x'>", 
    FireSpeed: "<img alt='FireSpeed' title='FireSpeed' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/566c9ff365dbbdab32ec0541/1x'>", 
    NaM: "<img alt='NaM' title='NaM' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/566ca06065dbbdab32ec054e/1x'>", 
    SourPls: "<img alt='SourPls' title='SourPls' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/566ca38765dbbdab32ec0560/1x'>", 
    FeelsSnowyMan: "<img alt='FeelsSnowyMan' title='FeelsSnowyMan' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/566decae65dbbdab32ec0699/1x'>", 
    LuL: "<img alt='LuL' title='LuL' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/567b00c61ddbe1786688a633/1x'>", 
    SaltyCorn: "<img alt='SaltyCorn' title='SaltyCorn' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/56901914991f200c34ffa656/1x'>", 
    monkaS: "<img alt='monkaS' title='monkaS' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/56e9f494fff3cc5c35e5287e/1x'>", 
    VapeNation: "<img alt='VapeNation' title='VapeNation' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/56f5be00d48006ba34f530a4/1x'>", 
    ariW: "<img alt='ariW' title='ariW' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/56fa09f18eff3b595e93ac26/1x'>", 
    notsquishY: "<img alt='notsquishY' title='notsquishY' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5709ab688eff3b595e93c595/1x'>", 
    FeelsAmazingMan: "<img alt='FeelsAmazingMan' title='FeelsAmazingMan' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5733ff12e72c3c0814233e20/1x'>", 
    DuckerZ: "<img alt='DuckerZ' title='DuckerZ' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/573d38b50ffbf6cc5cc38dc9/1x'>", 
    SqShy: "<img alt='SqShy' title='SqShy' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/59cf182fcbe2693d59d7bf46/1x'>", 
    Wowee: "<img alt='Wowee' title='Wowee' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/58d2e73058d8950a875ad027/1x'>", 
    WubTF: "<img alt='WubTF' title='WubTF' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5dc36a8db537d747e37ac187/1x'>", 
    cvR: "<img alt='cvR' title='cvR' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5e76d2ab8c0f5c3723a9a87d/1x'>", 
    cvL: "<img alt='cvL' title='cvL' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5e76d2d2d112fc372574d222/1x'>", 
    cvHazmat: "<img alt='cvHazmat' title='cvHazmat' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5e76d338d6581c3724c0f0b2/1x'>", 
    cvMask: "<img alt='cvMask' title='cvMask' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5e76d399d6581c3724c0f0b8/1x'>", 
    DogChamp: "<img alt='DogChamp' title='DogChamp' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5ffdf28dc96152314ad63960/1x'>", 
    PepoDance: "<img alt='PepoDance' title='PepoDance' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5a6edb51f730010d194bdd46/1x'>", 
    OMEGALUL: "<img alt='OMEGALUL' title='OMEGALUL' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/583089f4737a8e61abb0186b/1x'>", 
    PepeHands: "<img alt='PepeHands' title='PepeHands' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/59f27b3f4ebd8047f54dee29/1x'>", 
    Clap: "<img alt='Clap' title='Clap' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/55b6f480e66682f576dd94f5/1x'>", 
    pepeD: "<img alt='pepeD' title='pepeD' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5b1740221c5a6065a7bad4b5/1x'>", 
    pepeLaugh: "<img alt='pepeLaugh' title='pepeLaugh' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/59b73909b27c823d5b1f6052/1x'>", 
    HYPERS: "<img alt='HYPERS' title='HYPERS' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5980af4e3a1ac5330e89dc76/1x'>", 
    peepoHappy: "<img alt='peepoHappy' title='peepoHappy' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5a16ee718c22a247ead62d4a/1x'>", 
    jermaSheeto: "<img alt='jermaSheeto' title='jermaSheeto' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5c5629bc5e0cb51b417ffd1b/1x'>", 
    YOUDIED: "<img alt='YOUDIED' title='YOUDIED' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5c0235787991032d519f513c/1x'>", 
    jermaSuperFrog: "<img alt='jermaSuperFrog' title='jermaSuperFrog' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5df95b63c6f4490d9f858bee/1x'>", 
    jermaVroom2: "<img alt='jermaVroom2' title='jermaVroom2' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5d55d80364ae370ac8080707/1x'>", 
    jermaWalk: "<img alt='jermaWalk' title='jermaWalk' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5dfd48788608fb0da4120ec6/1x'>", 
    jermaOtto: "<img alt='jermaOtto' title='jermaOtto' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5e20fcb288e62a5f14dca2be/1x'>", 
    jermaPls: "<img alt='jermaPls' title='jermaPls' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5ec1e876ec17d81685a542d8/1x'>", 
    jermaWhat: "<img alt='jermaWhat' title='jermaWhat' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5ec6ada010aaa55e2946584a/1x'>", 
    jermaLoogame: "<img alt='jermaLoogame' title='jermaLoogame' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5ec1b6acec17d81685a53e06/1x'>", 
    jermaWild2: "<img alt='jermaWild2' title='jermaWild2' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5d65aa9d22f52e1d9b41da6a/1x'>", 
    jermaPunching: "<img alt='jermaPunching' title='jermaPunching' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5ec32c06f0fb3f168c4bcf23/1x'>", 
    jermaShirt: "<img alt='jermaShirt' title='jermaShirt' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5ebb0f14f0fb3f168c4b2e6c/1x'>", 
    jermaSlugPog: "<img alt='jermaSlugPog' title='jermaSlugPog' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5f5272e768d9d86c020dd15f/1x'>", 
    jermaOttoPet: "<img alt='jermaOttoPet' title='jermaOttoPet' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5f6cddf0c2f3a70b1ae5423d/1x'>", 
    peepoSnow: "<img alt='peepoSnow' title='peepoSnow' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5f91c1486f583802e38974aa/1x'>", 
    ChatPls: "<img alt='ChatPls' title='ChatPls' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5ecc80abfdee545e30654512/1x'>", 
    jermaGroovy: "<img alt='jermaGroovy' title='jermaGroovy' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5f72f7a5239b210b0de6b12d/1x'>", 
    jermaDillo: "<img alt='jermaDillo' title='jermaDillo' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5fc2b93a68e2d56f0f3a54e2/1x'>", 
    rareRat: "<img alt='rareRat' title='rareRat' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5f48111af93bbe5d717fe667/1x'>", 
    jermaApprove: "<img alt='jermaApprove' title='jermaApprove' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/5fbebaa40d141d6f06d84277/1x'>"
};

// Map of key (original) -> value (replacement)
var words = [];
// Push map keys onto array.
$.each(map, function(k) { words.push(k); });
// Regex to globally, case-insensitively match words. Note that this simplistic
// regex will treat punctuation like ' or - as word separators, so beware!
var regex = new RegExp("\\b(" + words.join("|") + ")\\b", "gi");
// Replacer function.
var replacer = function(value) { return map[value]; };

const getRandomMessage = async () => {
    const response = await fetch('https://jermai.scrypt.workers.dev', {
        method: 'GET',
        headers: {
            "Content-Type": "text/plain;charset=UTF-8"
        }
    });
    let data = await response.text(); //extract JSON from the http response
    console.log(data)
    return data;
    // document.getElementById("twitchChat").innerHTML = (twitchEmoji.parse( myJson.string ), { emojiSize : 'medium' } );
};

const colours = ["rgb(218, 165, 32)", "rgb(255, 69, 0)", "rgb(46, 139, 87)", "rgb(210, 105, 30)", "rgb(95, 158, 160)", "rgb(30, 144, 255)", "rgb(255, 105, 180)", "rgb(138, 43, 226)", "rgb(0, 255, 127)"];

const newMessage = async () => {
    var newMessage = await getRandomMessage();
    newMessage = newMessage.replace(":)", "<img alt='\:-?\)' title='\:-?\)' class='twitch-emote twitch-emote-0' src='https://static-cdn.jtvnw.net/emoticons/v1/1/1.0'>");
    newMessage = newMessage.replace("D:", "<img alt='D:' title='D:' class='twitch-emote twitch-emote-0' src='https://cdn.betterttv.net/emote/55028cd2135896936880fdd7/1x'>");
    newMessage = newMessage.replace(regex, replacer);
    var messageBox = document.createElement("span");
    var chatMessage = document.createElement("div");
    var chatMessage2 = document.createElement("div");
    var usernameSpan = document.createElement("span");
    usernameSpan.innerHTML = "aiJerm" + makeid(randomIntFromInterval(0, 10));
    usernameSpan.className = "username";
    usernameSpan.style.color = colours[Math.floor(Math.random() * colours.length)];
    chatMessage.appendChild(usernameSpan);
    messageBox.innerHTML += ":&nbsp;";
    messageBox.innerHTML += newMessage;
    messageBox.className = "messageBox";
    chatMessage.className = "chatMessage";
    chatMessage2.className = "chatMessage2";
    chatMessage.appendChild(messageBox);
    chatMessage2.appendChild(chatMessage);
    document.getElementById("chatContainer").appendChild(chatMessage2);
    if(document.getElementById("scroll").checked === true) {
        window.scrollTo(0,document.body.scrollHeight);
    }
};

(function loop() {
    var rand = randomIntFromInterval(4000, 5000);
    setTimeout(function() {
        newMessage();
            loop();  
    }, rand);
}());

function makeid(length) {
    var result           = '';
    var characters       = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    var charactersLength = characters.length;
    for ( var i = 0; i < length; i++ ) {
       result += characters.charAt(Math.floor(Math.random() * charactersLength));
    }
    return result;
 }

function randomIntFromInterval(min, max) { // min and max included 
    return Math.floor(Math.random() * (max - min + 1) + min);
}
