name: Purge Cloudflare Cache
on:
  page_build

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Purge cache
      uses: jakejarvis/cloudflare-purge-action@master
      env:
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}

        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        PURGE_URLS: '["https://aichat.jerma.io/index.html", "https://aichat.jerma.io/styles.css", "https://aichat.jerma.io/scripts.js"]'
